

export const GET_TABLE_HEADERS_PENDING='GET_TABLE_HEADERS_PENDING';
export const GET_TABLE_HEADERS_FULFILLED='GET_TABLE_HEADERS_FULFILLED';
export const GET_TABLE_HEADERS_REJECTED='GET_TABLE_HEADERS_REJECTED';

export const GET_TABLE_ROWS_PENDING='GET_TABLE_ROWS_PENDING';
export const GET_TABLE_ROWS_FULFILLED='GET_TABLE_ROWS_FULFILLED';
export const GET_TABLE_ROWS_REJECTED='GET_TABLE_ROWS_REJECTED';

